plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.testan'
    compileSdk 35

    def buildTimestamp = (System.currentTimeMillis() / 1000).toInteger()

    defaultConfig {
        applicationId "com.example.testan"
        minSdk 24
        targetSdk 35
        versionCode buildTimestamp
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('release.keystore')
            storePassword 'testan123'
            keyAlias 'testan'
            keyPassword 'testan123'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
    implementation 'androidx.fragment:fragment:1.8.5'
}